version: '3.1'

services:
  db:
    container_name: zio-quill-gettingstarted
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 25432:5432
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d/:ro
